# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1e43b6c12d5481a59a904ce63958899c6fb8bf9fc76edd2ef84d5db3017f6757399889146975deaf74ec32de1d6345b28c3a5195f46eda9940a2301d54a7af6

test:
  secret_key_base: 840626db73a6e0e2cbefbf01b01d1ac1d1cdd507d2459c4ad9f754e6ab954f2e8179ff6c46294f0e459b27db54bd33644bd03f88f4e2bee84f902c54b264d85e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
